:wrench: test

diff --git a/.github/workflows/golang-binary-release.yaml b/.github/workflows/golang-binary-release.yaml
--- a/.github/workflows/golang-binary-release.yaml
+++ b/.github/workflows/golang-binary-release.yaml
@@ -27,14 +27,21 @@ jobs:
   goreleaser:
     name: "Run Goreleaser"
     runs-on: ubuntu-24.04
-    # if: ${{ github.event.base_ref }} == 'refs/heads/${{ github.event.repository.default_branch }}'
-    if: |
-      (startsWith(github.ref, 'refs/heads/') && github.ref == 'refs/heads/${{ github.event.repository.default_branch }}) ||
-      (startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/${{ github.event.repository.default_branch }}')
-
     steps:
-      # - if: ${{ github.event.base_ref }} == 'refs/heads/${{ github.event.repository.default_branch }}'
-      #  run: echo "${{ github.event.base_ref }} == refs/heads/${{ github.event.repository.default_branch }}" ; exit 1
+      - name: Validate only default branch or tags
+        run: |
+          ref="${{ github.ref }}"
+          default_branch="${{ github.event.repository.default_branch }}"
+
+          echo "Current ref: $ref"
+          echo "Default branch: $default_branch"
+
+          if [[ "$ref" != "refs/heads/$default_branch" && ! "$ref" =~ ^refs/tags/ ]]; then
+            echo "❌ Invalid ref: $ref. Only default branch ($default_branch) or tags allowed."
+            exit 1
+          fi
+
+          echo "✅ Valid ref: $ref"
 
       - uses: actions/checkout@v4
 
